### ISSUE TITLE
Design a way to pass clock handles into commands

### ISSUE THREAD

**Issue by kulakowski-wasm** [bytecodealliance/wasi-libc#12]

**Comment by kulakowski-wasm** [comment]
@sunfishcode we'd noted this one as a libc task, and I can imagine there's some plumbing work there. Is there anything else needed? say in wit-bindgen to name a particular clock capability?

**Comment by sunfishcode** [comment]
Once https://github.com/WebAssembly/wasi-clocks/pull/14 lands, I'll submit a PR to wasi-clocks.wit.md define a default clock handle value export that programs can import. Then, once wit-bindgen has support for value imports/exports, it should be straightforward to write the code in wasi-libc to use it.

**Comment by sunfishcode** [comment]
I've now submitted https://github.com/WebAssembly/wasi-clocks/pull/15 to propose the Wit API for this.

**Comment by kulakowski-wasm** [comment]
This is done.
